name: codacy coverage reporter
on:
  pull_request:
    types:
      - opened
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - name: pull repository
        uses: actions/checkout@v4
      - name: setup program language libraries -  python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install dependencies - python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: setup program language libraries -  java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: install dependencies - java
        run: |
          sudo apt-get install maven -y
      - name: run test with coverage
        run: |
          cd python
          coverage run -m unittest discover
          coverage report -m
          coverage xml
      - name: upload code coverage report to codacy - python
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: python/coverage.xml
      - name: build and test java
        run: |
          ls -l
          cd java
          mvn clean test
          mvn jacoco:report
      - name: upload code coverage report to codacy - java
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: java/target/site/jacoco/jacoco.xml